# Generated by Django 4.0.4 on 2022-07-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='default.jpg', max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de Perfil'),
        ),
    ]
