# Generated by Django 4.0.4 on 2022-07-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calzados',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indumentarias',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
